/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionDotjsonRouteImport } from './routes/version[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as Icon512DotpngRouteImport } from './routes/icon-512[.]png'
import { Route as Icon192DotpngRouteImport } from './routes/icon-192[.]png'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaviconDotpngRouteImport } from './routes/favicon[.]png'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AppleTouchIconDotpngRouteImport } from './routes/apple-touch-icon[.]png'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VersionDotjsonRoute = VersionDotjsonRouteImport.update({
  id: '/version.json',
  path: '/version.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const Icon512DotpngRoute = Icon512DotpngRouteImport.update({
  id: '/icon-512.png',
  path: '/icon-512.png',
  getParentRoute: () => rootRouteImport,
} as any)
const Icon192DotpngRoute = Icon192DotpngRouteImport.update({
  id: '/icon-192.png',
  path: '/icon-192.png',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotpngRoute = FaviconDotpngRouteImport.update({
  id: '/favicon.png',
  path: '/favicon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AppleTouchIconDotpngRoute = AppleTouchIconDotpngRouteImport.update({
  id: '/apple-touch-icon.png',
  path: '/apple-touch-icon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/gallery': typeof GalleryRoute
  '/icon-192.png': typeof Icon192DotpngRoute
  '/icon-512.png': typeof Icon512DotpngRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.json': typeof VersionDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/gallery': typeof GalleryRoute
  '/icon-192.png': typeof Icon192DotpngRoute
  '/icon-512.png': typeof Icon512DotpngRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.json': typeof VersionDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apple-touch-icon.png': typeof AppleTouchIconDotpngRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/gallery': typeof GalleryRoute
  '/icon-192.png': typeof Icon192DotpngRoute
  '/icon-512.png': typeof Icon512DotpngRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pricing': typeof PricingRoute
  '/programs': typeof ProgramsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/version.json': typeof VersionDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apple-touch-icon.png'
    | '/coaches'
    | '/contact'
    | '/favicon.ico'
    | '/favicon.png'
    | '/gallery'
    | '/icon-192.png'
    | '/icon-512.png'
    | '/manifest.webmanifest'
    | '/pricing'
    | '/programs'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/version.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apple-touch-icon.png'
    | '/coaches'
    | '/contact'
    | '/favicon.ico'
    | '/favicon.png'
    | '/gallery'
    | '/icon-192.png'
    | '/icon-512.png'
    | '/manifest.webmanifest'
    | '/pricing'
    | '/programs'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/version.json'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apple-touch-icon.png'
    | '/coaches'
    | '/contact'
    | '/favicon.ico'
    | '/favicon.png'
    | '/gallery'
    | '/icon-192.png'
    | '/icon-512.png'
    | '/manifest.webmanifest'
    | '/pricing'
    | '/programs'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/version.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppleTouchIconDotpngRoute: typeof AppleTouchIconDotpngRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FaviconDotpngRoute: typeof FaviconDotpngRoute
  GalleryRoute: typeof GalleryRoute
  Icon192DotpngRoute: typeof Icon192DotpngRoute
  Icon512DotpngRoute: typeof Icon512DotpngRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PricingRoute: typeof PricingRoute
  ProgramsRoute: typeof ProgramsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VersionDotjsonRoute: typeof VersionDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version.json': {
      id: '/version.json'
      path: '/version.json'
      fullPath: '/version.json'
      preLoaderRoute: typeof VersionDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon-512.png': {
      id: '/icon-512.png'
      path: '/icon-512.png'
      fullPath: '/icon-512.png'
      preLoaderRoute: typeof Icon512DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon-192.png': {
      id: '/icon-192.png'
      path: '/icon-192.png'
      fullPath: '/icon-192.png'
      preLoaderRoute: typeof Icon192DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.png': {
      id: '/favicon.png'
      path: '/favicon.png'
      fullPath: '/favicon.png'
      preLoaderRoute: typeof FaviconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apple-touch-icon.png': {
      id: '/apple-touch-icon.png'
      path: '/apple-touch-icon.png'
      fullPath: '/apple-touch-icon.png'
      preLoaderRoute: typeof AppleTouchIconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppleTouchIconDotpngRoute: AppleTouchIconDotpngRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FaviconDotpngRoute: FaviconDotpngRoute,
  GalleryRoute: GalleryRoute,
  Icon192DotpngRoute: Icon192DotpngRoute,
  Icon512DotpngRoute: Icon512DotpngRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PricingRoute: PricingRoute,
  ProgramsRoute: ProgramsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VersionDotjsonRoute: VersionDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
